# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c59a7b68f788e0a8303669467dfee8bfa0cd6324addc06bd0a510a3f4676e2ad8d6682c132d9caf1a875fed7cd43056677e04b46ff510fffdc9b636604af664e

test:
  secret_key_base: d95182efa1cd78d4071cc1e712d3f3d404a453e3d427e6ea95bd9e10aa4a2fbfd232b0959cd59ea0a7309efd73d122c29d91b7c4e8d9f4020db02501d90b13e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
